kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30100
        hostPort: 9100
        protocol: TCP
      - containerPort: 30180
        hostPort: 9180
        protocol: TCP
      - containerPort: 30006
        hostPort: 9006
        protocol: TCP
