[request_definition]
r = sub, org, obj, act

[policy_definition]
p = sub, org, obj, act, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (r.sub == p.sub || p.sub == "*") && (r.org == p.org || p.org == "*") && (r.obj == p.obj || p.obj == "*") && (r.act == p.act || p.act == "*")
