{{- if and .Values.podDisruptionBudgets.enabled (gt (int .Values.strongholdApi.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stronghold.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: stronghold-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "stronghold.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: stronghold-api
{{- end }}
