apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stronghold.serviceAccountName.phoenix" . }}
  namespace: {{ include "stronghold.namespace" . }}
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix
    stronghold.io/rbac-tier: phoenix
  {{- with .Values.serviceAccounts.phoenix.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
