apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stronghold.serviceAccountName.postgres" . }}
  namespace: {{ include "stronghold.namespace" . }}
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    stronghold.io/rbac-tier: postgres
  {{- with .Values.serviceAccounts.postgres.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
