apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stronghold.serviceAccountName.strongholdApi" . }}
  namespace: {{ include "stronghold.namespace" . }}
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: stronghold-api
    stronghold.io/rbac-tier: stronghold-api
  {{- with .Values.serviceAccounts.strongholdApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
