apiVersion: v1
kind: Service
metadata:
  name: {{ include "stronghold.fullname" . }}-phoenix
  namespace: {{ include "stronghold.namespace" . }}
  labels:
    {{- include "stronghold.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix
    stronghold.io/priority-tier: P1
spec:
  type: ClusterIP
  selector:
    {{- include "stronghold.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix
  ports:
    - name: http
      port: {{ .Values.phoenixSvc.containerPort }}
      targetPort: http
      protocol: TCP
