apiVersion: v1
kind: Service
metadata:
  name: turing
  namespace: turing
  labels:
    app: turing
spec:
  type: NodePort
  selector:
    app: turing
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      nodePort: 30910
    - name: chat
      port: 9101
      targetPort: chat
      nodePort: 30911
